app = "pied-piper-dashboard"
primary_region = "lax"
port = 8080

[build]
  dockerfile = "Dockerfile"

[env]
  DASH_USER = "alim"
  DASH_PASS = "middleout2026"
  PORT = "8080"
  FLASK_ENV = "production"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
s  {
    port = 8080
    handlers = ["http"]
  }

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1